parameters:
  appVersion: "1.4.6"
  appName: "K24.ing"
  fullAppName: "K24.ing"
  noReply: "no-reply@k24.ing"
  webMasterName: "Webmaster"
  webMasterEmail: "demo@khalilleo.com"
  phoneNumber: '0163/616-5396'
  infoEmail: 'info@khalilleo.com'
  legalEmail: 'legal@khalilleo.com'

  addressStreet: 'Paul-Gerhardt-Str. 7'
  addressPlz: '74321'
  addressCity: 'Bietigheim-Bissingen'
  addressCountry: 'Deutschland'

  appAuthor: "Khalilleo Teams"
  appCreated: "2024-03-03"
  poweredBy: "khalilleo.com"
  avatarDir: "%kernel.project_dir%/public/avatar"