parameters:
  app_name: "ELE"
  full_app_name: "Ele.click"
  no_reply: "no-reply@khalilleo.com"
  app_author: "Khalilleo Teams"
  app_created: "2024-03-03"
  app_version: "1.0.2"
  app_made_by: "khalilleo.com"
